title: Time Machine theme
logo: WhatsApp Image 2025-02-18 at 14.36.14_6b5ac9a4.jpg
show_downloads: true
google_analytics:
theme: jekyll-theme-time-machine

description: >-
  Lead Data Analyst | Power BI | Tableau | SQL | Excel |
  Helping businesses make data-driven decisions with clear, compelling dashboards.
